export const myTasks = [
  {
    id: 1,
    text: "Doctors Appointment",
    day: "Feb 5th at 2:30pm",
    reminder: true,
    category: "health",
    check: false,
  },
  {
    id: 2,
    text: "Meeting at school",
    day: "Feb 6th at 4:30pm",
    reminder: true,
    category: "education",
    check: false,
  },
  {
    id: 3,
    text: "Food shopping",
    day: "Feb 5th at 1:30pm",
    reminder: false,
    category: "food",
    check: false,
  },
  {
    id: 4,
    text: "Gym lesson",
    day: "Feb 5th at 6:30pm",
    reminder: false,
    category: "sport",
    check: false,
  },
  {
    id: 5,
    text: "The diner time",
    day: "Feb 5th at 8:30pm",
    reminder: true,
    category: "food",
    check: false,
  },
];
